import express from "express";
import cors from "cors";
import routes from "./routes";
import mongooseConnection from "./database/Mongoose";
mongooseConnection();
const app = express();
app.use(cors());
app.use(express.json());
app.use(routes);
// app.use(router);
app.listen(4000, () => console.log("Running at 4000"));
